services:
  - type: web
    name: auth-backend
    env: java
    plan: free
    buildCommand: ./mvnw -DskipTests package
    startCommand: java -jar target/auth-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SERVER_PORT
        value: 8080
      - key: DB_URL
        value: jdbc:mysql://sql12.freesqldatabase.com:3306/sql12809246
      - key: DB_USER
        value: sql12809246
      - key: DB_PASS
        value: aXGYQCgwxv
